openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Multi-file boilerplate for OpenAPI Specification.
  license:
    name: MIT
  contact:
    name: API Team
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
paths:
  /pets:
    $ref: "./resources/pets.yml"
  /pets/{petId}:
    $ref: "./resources/pet.yml"
components:
  parameters:
    $ref: "./parameters/_index.yml"
  schemas:
    $ref: "./schemas/_index.yml"
  responses:
    $ref: "./responses/_index.yml"